# Creates Replicaset 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 3
  strategy: 
    # type: Recreate
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: 355449129696.dkr.ecr.us-east-1.amazonaws.com/cart:005
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
                name: cart-configmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-configmap
data:
  REDIS_HOST: roboshop-dev-redis.8m1fwx.0001.use1.cache.amazonaws.com
  CATALOGUE_HOST: catalogue-svc
--- 

apiVersion: v1
kind: Service
metadata:
  name: cart-svc
spec:
  selector:
     app: cart
  ports:
    - protocol: TCP
      port: 8080                         # Port number that your service has to listen and this is the port you will access
      targetPort: 8080                   # TargetPort forwards the requests to the backend pod


---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cart-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 75
